### ISSUE TITLE
how to save file after finish edit?

### ISSUE THREAD

**Issue by yamihana** [torocc/KoikatuSaveDataEdit#1]
just cannot find save button
if this Project have save button, maybe your program window is too large for my screen size(1366x768)

**Comment by torocc** [comment]
Save & quit button is bottom of window. left of quit button.

Is not it displayed?

**Comment by yamihana** [comment]
yes, i cannot scroll down to bottom of window (stuck in last character before Save & quit button appear)
i tried to decrease the number of student but..... don't know
![image]
![capture](https://user-images.githubusercontent.com/39035153/39691166-cf6e2604-5206-11e8-8570-dc80928fe15c.JPG)
